version: '3.0'
services:
  mongo:
    image: mongo:latest
    networks: 
      - sepro-network
    ports: 
      - "27017:27017"
    restart: always

  frontend:
    build: 
      context: .
      dockerfile: ./src/Frontend/Dockerfile
    networks: 
      - sepro-network
    ports: 
      - "3000:3000"
    depends_on: 
      - backend
    restart: always

  backend:
    build: 
      context: .
      dockerfile: ./src/Backend/Dockerfile
    networks: 
      - sepro-network
    ports: 
      - "5001:5001"
    depends_on: 
      - mongo
    restart: always

networks:
  sepro-network:
    driver: bridge